apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- include "app.apoloPodLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.modelDownload.initEnabled }}
      initContainers:
        - name: download-model
          image: "{{ .Values.modelDownload.image.repository }}:{{ .Values.modelDownload.image.tag }}"
          volumeMounts:
            {{- if .Values.HFCacheVolume.enabled }}
            - name: huggingface-cache
              mountPath: /root/.cache/huggingface
            {{- end }}
          env:
          {{- range $k, $v := .Values.env }}
          - name: {{ $k }}
            {{- if kindIs "string" $v }}
            value: {{ $v | quote }}
            {{- else }}
            {{- $v | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
          command: ["huggingface-cli"]
          args:
            - download
            - --resume-download
            - --repo-type=model
            {{- if .Values.model.modelRevision }}
            - --revision={{ .Values.model.modelRevision }}
            {{- end }}
            - "{{ .Values.model.modelHFName }}"
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # Startup probe – generous grace period for cold start
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: {{ .Values.probe.startup.periodSeconds }}
            failureThreshold: {{ .Values.probe.startup.failureThreshold }}
            timeoutSeconds: {{ .Values.probe.startup.timeoutSeconds }}

          # Liveness probe – steady‑state, no delay
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probe.liveness.failureThreshold }}
            timeoutSeconds: {{ .Values.probe.liveness.timeoutSeconds }}

          # Readiness probe – tight cadence
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probe.readiness.failureThreshold }}
            timeoutSeconds: {{ .Values.probe.readiness.timeoutSeconds }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            {{- if .Values.HFCacheVolume.enabled }}
            - name: huggingface-cache
              mountPath: /huggingface-cache
            {{- end }}
          env:
            - name: HUGGINGFACE_HUB_CACHE
              value: /huggingface-cache
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              {{- if kindIs "string" $v }}
              value: {{ $v | quote }}
              {{- else }}
              {{ $v | toYaml | nindent 14 }}
              {{- end }}
            {{- end }}
          args:
            - --hostname=0.0.0.0
            - --port={{ .Values.service.port }}
            - --model-id={{ .Values.model.modelHFName }}
            {{- if .Values.model.modelRevision }}
            - --revision={{ .Values.model.modelRevision }}
            {{- end }}
          {{- with .Values.serverExtraArgs -}}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      {{- if .Values.HFCacheVolume.enabled }}
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: {{ include "app.hfcachename" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
