image:
  tag: hopper-1.2.3

model:
  modelHFName: "nomic-ai/nomic-embed-text-v1"

ingress:
  enabled: true
  clusterName: scottdc
  forwardAuth:
    enabled: false
    # name: forwardauth
    # address: http://forwardauth:8080
    # trustForwardHeader: true
    # authRequestHeaders:
    #   - "Cookie"
    #   - "Authorization"

preset_name: H100x1
