nameOverride: ""
fullnameOverride: ""

# Deployment
model:
  modelHFName: ""
  modelRevision:

serverExtraArgs: []

replicaCount: 1

image:
  repository: ghcr.io/huggingface/text-embeddings-inference
  pullPolicy: IfNotPresent
  tag: "1.2.3"
  imagePullSecrets: []

resources: {}

healthChecksDelay: 30

HFCacheVolume:
  enabled: true
  storage: 20Gi
  accessMode: ReadWriteOnce

env:
  HUGGING_FACE_HUB_TOKEN: ""

podAnnotations: {}

nodeSelector: {}

tolerations:
  - key: platform.neuromation.io/job
    operator: Exists
    effect: NoSchedule
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

affinity: {}

priorityClassName: ""

# Model download hook
modelDownload:
  initEnabled: true
  image:
    repository: ghcr.io/neuro-inc/hf-downloader
    tag: v25.4.0
    pullPolicy: IfNotPresent
  resources: {}

# Service
service:
  port: 3000

# Ingress
ingress:
  enabled: false
  clusterName: ""
  forwardAuth:
    enabled: false
    # name: forwardauth
    # address: http://forwardauth:8080
    # trustForwardHeader: true
    # authRequestHeaders:
    #   - "Cookie"
    #   - "Authorization"

preset_name: ""
