nameOverride: ""
fullnameOverride: ""

# Deployment
model:
  modelHFName: ""
  modelRevision:

serverExtraArgs: []

replicaCount: 1

image:
  repository: ghcr.io/huggingface/text-embeddings-inference
  pullPolicy: IfNotPresent
  tag: "1.2.3"
  imagePullSecrets: []

resources: {}

healthChecksDelay: 30

HFCacheVolume:
  enabled: true
  storage: 20Gi
  accessMode: ReadWriteOnce

env:
  HUGGING_FACE_HUB_TOKEN: ""

podAnnotations: {}

nodeSelector: {}

tolerations:
  - key: platform.neuromation.io/job
    operator: Exists
    effect: NoSchedule
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

affinity: {}

priorityClassName: ""

# Model download hook
modelDownload:
  initEnabled: true
  image:
    repository: huggingface/downloader
    tag: 0.17.3
    pullPolicy: IfNotPresent
  resources: {}

# Service
service:
  port: 3000

# Ingress
ingress:
  enabled: false
  clusterName: ""

preset_name: ""
